# Generated by Django 6.0.7 on 2026-07-17 02:27

import core.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Prontuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paciente_nome', core.fields.EncryptedCharField(max_length=100)),
                ('cpf', core.fields.EncryptedCharField(max_length=11)),
                ('queixa_principal', core.fields.EncryptedTextField()),
                ('evolucao_queixa', core.fields.EncryptedTextField()),
                ('historico_tratamento', core.fields.EncryptedTextField()),
                ('tags_busca', models.CharField(blank=True, max_length=255)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
